### ISSUE TITLE
UnfinishedVerificationException with Kotlin after updating to 2.9.0

### ISSUE THREAD

**Issue by ming13** [mockito/mockito#1183]
Mockito update 2.8.47 → 2.9.0 brought us the exception when running the following test.

```kotlin
package redacted.package.name

import org.junit.Test
import org.mockito.Mockito.spy
import org.mockito.Mockito.verify

class MockitoTest {

    @Test fun test() {
        val value = spy({})
        value.invoke()

        verify(value).invoke()
    }

    @Test fun testAgain() {
        val value = spy({})
        value.invoke()

        verify(value).invoke()
    }
}
```

```
org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Missing method call for verify(mock) here:
-> at redacted.package.name.MockitoTest.testAgain(MockitoTest.kt:20)

Example of correct verification:
    verify(mock).doSomething()

Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
Those methods *cannot* be stubbed/verified.
Mocking methods declared on non-public parent classes is not supported.

	at redacted.package.name.MockitoTest.test(MockitoTest.kt:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
``` 

Please notice that the following test will produce no errors.

```kotlin
package redacted.package.name

import org.junit.Test
import org.mockito.Mockito.spy
import org.mockito.Mockito.verify

class MockitoTest {

    @Test fun test() {
        val value = spy({})
        value.invoke()

        verify(value).invoke()
    }
}
```

This works as well, so I assume it can be Kotlin-lamda-related.

```kotlin
package redacted.package.name

import io.reactivex.functions.Action
import org.junit.Test
import org.mockito.Mockito.spy
import org.mockito.Mockito.verify

class MockitoTest {

    class ActionImpl : Action {
        override fun run() = Unit
    }

    @Test fun test() {
        val value = spy(ActionImpl())
        value.run()

        verify(value).run()
    }

    @Test fun testAgain() {
        val value = spy(ActionImpl())
        value.run()

        verify(value).run()
    }
}
```

Also, important detail. Running from IDE works fine, only Gradle runner is affected.

```
./gradlew :module:testDebugUnitTest
```

**Comment by ming13** [comment]
FYI the same thing happens with Mockito 2.10.0.

**Comment by raphw** [comment]
Should be fixed on master already.

**Comment by ming13** [comment]
@raphw Can you please point me at the commit?

**Comment by raphw** [comment]
https://github.com/mockito/mockito/commit/9848cec9ebb28791bca565200cdacf337730a015

**Comment by ming13** [comment]
@raphw Just double-checked 2.10.0 and the issue is still the same 😞

**Comment by raphw** [comment]
The commit is not yet pushed out, I think.

**Comment by raphw** [comment]
Ah, too bad. I will have a look. It surely is related to our performance optimizations of detecting overridden calls to avoid repeated mocking down the hierarchy.

**Comment by ming13** [comment]
The issue remains when using 2.11.0 as well.

**Comment by raphw** [comment]
I have added a test case on a branch now and started investigating. Seems like there is some issue with the sefl-invocation check such that the apply call is not recognized as a mock invocation.

**Comment by raphw** [comment]
It seems like this is an issue within bridge method resolution. Kotlin creates several methods with equal Java signature. Given test test class:
```java
class example.FunctionTest$testAgain$value$1
```

The Kotlin compiler implements two methods:
```java
public java.lang.Object example.FunctionTest$testAgain$value$1.invoke()
public final void example.FunctionTest$testAgain$value$1.invoke()
```

From the view of the Java language, these two methods have an identical invocation signature and Byte Buddy attempts to resolve one method as a bridge method of the other one what is a mistake.

I am currently trying to figure out why Kotlin is doing that, this would also break interoperability from Java. Unfortunately, this is not an easy mistake to work around either as we need to resolve bridge methods in order to handle Java classes correctly. And even with Kotlin, Java classes will always be involved via the core class library such that one cannot simply offer a language switch.

The fact that this broke recently is a result of fixing this resolution for Java which was necessary due to a bug in this mechanism.

**Comment by ming13** [comment]
Just checked the 2.12.0 and the issue seems to be fixed indeed. Thanks!
