### ISSUE TITLE
Mock returning java.util.Optional should return Optional.empty() by default (Java 8)

### ISSUE THREAD

**Issue by netmikey** [mockito/mockito#191]
(From the discussion at https://code.google.com/p/mockito/issues/detail?id=497 )

> A stubbed method that returns `Optional<?>` should return `Optional.empty()` if no explicit behavior is defined. This is equivalent to returning null for regular methods.
> 
> Introducing this feature would add no extra dependencies. However, it would require a test whether the code is running in Java 8.

Since the thread ends with the request for a GitHub ticket and I couldn't find one... here it is :)

**Comment by phjardas** [comment]
I've implemented a default answer for Optional. The code uses reflection so it should still compile and run cleanly on Java versions below 8.

However, I have absolutely no idea how to test this code, because it would require two different JDKs to test both branches.

**Comment by olivergierke** [comment]
Hey all, what's the status on this? We're porting quite a big codebase to Java 8 currently and it's quite a PITA to have to define behavior to mock all methods returning `Optional` now. Is there an ETA for when this will be available in a release?

**Comment by phjardas** [comment]
I've submitted the fix #192 more than a year ago... 😞

**Comment by raphw** [comment]
I will try to look at some of the outstanding issues until the end of July. Sorry, I am really busy with Java 9 adoption in Byte Buddy since the last half year, there is a lot to do but this is still happening, no worries.

**Comment by raphw** [comment]
I just merged your PR on my machine and rebased it to the current state. I also wrote the missing unit test to validate this. I am currently traveling and the local Wifi does not open a port for SSH. I'll push to master tonight and trigger a new build.

**Comment by phjardas** [comment]
Great! Thanks a lot. Shall I write some more for Iterable and Stream?

**Comment by raphw** [comment]
Yes, please. I will try to get them out in short time, this basic Java 8 support is really about time to be added.

**Comment by phjardas** [comment]
Will do once you have merged the first PR. 👍

**Comment by olivergierke** [comment]
Wow, guys. You rock! 🤘. What's the story with the version numbers? There are a lot of 2.0 betas on Maven central already? Are these preview versions for 3.0?

**Comment by TimvdLippe** [comment]
@olivergierke these are 2.0-beta versions. We are planning to release Mockito 2.0 soonTM. (lot's of delay due to IRL projects)

**Comment by olivergierke** [comment]
How's that going to work? Everything 2.0.x will rank lower in sorting than the already released betas, won't it?

**Comment by phjardas** [comment]
@raphw here's `java.util.stream.Stream`, as promised --> #429

**Comment by dnouls** [comment]
Is this still not merged in Mockito ? I’m currently using 2.8.9 and I still get null iso Optional.empty()

**Comment by szpak** [comment]
@dnouls It should work. Please open an another ticket with a test case.

**Comment by dnouls** [comment]
False report! I had a NPE elsewhere. Using stream API's and Optionals sometimes make it hard to debug properly.
