### ISSUE TITLE
Mockito can't create mock on public class that extends package-private class

### ISSUE THREAD

**Issue by astafev** [mockito/mockito#216]
I created simple project to demonstrate this:
https://github.com/astafev/mockito-package-private-class/

Please take a look. Even if it can't be implemented, I think that mockito should throw some normal exception at time of creation.
In my variant on first creation it returns wrong-working mock (invokes real method instead of stubbed). On second creation throws exception that doesn't really connected with problem.

Everything works fine if you mock package-private parent.

**Comment by astafev** [comment]
it's both actual for 1.10.19 and 2.0.2-beta versions.

**Comment by bric3** [comment]
It is a known issue with CGLIB and it is raised there too #168, by merging #171 (replacing CGLIB by ByteBuddy) it should fix the problem.

For reference in the old issue tracker : https://code.google.com/p/mockito/issues/detail?id=212

**Comment by astafev** [comment]
it's good that it's known problem. But the main problem is that it takes a lot of time to find out real cause. Please consider adding special exception, because exceptions that raised currently really confuse.

**Comment by bric3** [comment]
Note #171 is merged, you may want to give the latest beta a try. But note that public API is subject to change when it is released and during develoment.

**Comment by takecare** [comment]
i'm still experiencing this issue (with the latest beta: 2.0.52-beta)
